### 1. 라이브러리를 사용하기 위해서 모듈을 로드(import)
    - import 라이브러리 명 (import pandas)
    - from pandas import Series, DataFrame
    - import pandas as pd

In [1]:
from pandas import Series, DataFrame
import pandas as pd

In [2]:
fruit = Series(data=[2500, 3800, 1200, 6000], index=['apple','banana','pear','cherry'])
#data와 index 선언 생략하고 써도 동일하다. 단, 생략했을 경우 순서대로 인식한다.
#데이터 타입도 알아서 지정해준다.

In [3]:
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [5]:
pd.Series([2500,3800,1200,6000],['apple','banana','pear','cherry']);fruit
#이건 import pandas as pd에서 가져오는 데이터이다.

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [6]:
#특정갑 추출

In [7]:
fruit.values

array([2500, 3800, 1200, 6000], dtype=int64)

In [12]:
print(fruit.values)

[2500 3800 1200 6000]


In [8]:
fruit.index

Index(['apple', 'banana', 'pear', 'cherry'], dtype='object')

In [13]:
print(fruit.index)

Index(['apple', 'banana', 'pear', 'cherry'], dtype='object')


In [14]:
fruitData = {'apple':2500, 'banana':3800, 'pear':1200, 'cherry':6000}
fruit = Series(fruitData)
#딕셔너리와 시리즈 데이터가 유사해보이지만 기본적인 type을 다르게 처리

In [15]:
type(fruitData)

dict

In [16]:
type(fruit)

pandas.core.series.Series

In [17]:
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [20]:
fruit.name = 'fruitPrice'
fruit.index.name = 'fruitName'
fruit

fruitName
apple     2500
banana    3800
pear      1200
cherry    6000
Name: fruitPrice, dtype: int64

## DataFrame 생성

In [23]:
fruitData = {'fruitName':['apple', 'banana', 'cherry', 'pear'],
            'fruitPrice':[2500, 3800, 6000, 1200],
            'num' : [10, 5, 3, 8]} #인덱스는 자동으로 배치 / 대응이 되도록 개수를 잘 맞워야 함.
fruitFrame = DataFrame(fruitData)
print(fruitFrame)

  fruitName  fruitPrice  num
0     apple        2500   10
1    banana        3800    5
2    cherry        6000    3
3      pear        1200    8


In [25]:
fruitFrame

fruitName  fruitPrice  num
0     apple        2500   10
1    banana        3800    5
2    cherry        6000    3
3      pear        1200    8

In [26]:
fruitFrame.info() #인포에서 하나라도 object라면 object로 인식 > 프로그램이 처리하기 가장 쉬운 타입으로 인식하기 때문

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   fruitName   4 non-null      object
 1   fruitPrice  4 non-null      int64 
 2   num         4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [27]:
fruitData = {'fruitName':['apple', 'banana', 'cherry', 'pear'],
            'fruitPrice':[2500, 3800, 6000, 1200],
            'num' : [10, 5, 3, 8]}
fruitFrame = DataFrame(fruitData, columns=['fruitName', 'fruitPrice', 'num'])
#키가 있는 데이터는 column값과 키값이 일치해야 value값을 불러올 수 있다.

In [28]:
fruitFrame

fruitName  fruitPrice  num
0     apple        2500   10
1    banana        3800    5
2    cherry        6000    3
3      pear        1200    8

In [31]:
import numpy as np

df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]) #키가 없는 데이터는 column값을 줘서 키를 만들 수 있다.
                  ,columns=['a','b','c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [32]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
fruitFrame

fruitName  fruitPrice  num
0     apple        2500   10
1    banana        3800    5
2    cherry        6000    3
3      pear        1200    8

In [36]:
#특정 column을 불러올 때 사용
fruitFrame['fruitName']

0     apple
1    banana
2    cherry
3      pear
Name: fruitName, dtype: object

In [37]:
type(fruitFrame['fruitName'])

pandas.core.series.Series

In [38]:
fruitFrame.fruitName

0     apple
1    banana
2    cherry
3      pear
Name: fruitName, dtype: object

In [43]:
#column을 추가하는 방법
fruitFrame['year'] = 2016
fruitFrame

fruitName  fruitPrice  num  year
0     apple        2500   10  2016
1    banana        3800    5  2016
2    cherry        6000    3  2016
3      pear        1200    8  2016

In [44]:
val=Series([4,2,1], index=[0,2,3])
val

0    4
2    2
3    1
dtype: int64

In [45]:
fruitFrame['stock'] = val #인덱스값이 일치하는 곳에 value값을 추가
fruitFrame

fruitName  fruitPrice  num  year  stock
0     apple        2500   10  2016    4.0
1    banana        3800    5  2016    NaN
2    cherry        6000    3  2016    2.0
3      pear        1200    8  2016    1.0

## 데이터 구조 항목 삭제

In [46]:
fruit = Series(data=[2500, 3800, 1200, 6000], index=['apple','banana','pear','cherry'])
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [47]:
fruit.drop('banana') #삭제된 것처럼 보이지만 원래 데이터 값을 삭제한 것은 아님.

apple     2500
pear      1200
cherry    6000
dtype: int64

In [48]:
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [49]:
fruit.drop('banana', inplace=True) #drop명령에서 inplace가 False여야 원본 데이터의 손실이 없다.
fruit

apple     2500
pear      1200
cherry    6000
dtype: int64

In [53]:
fruitData = {'fruitName':['apple', 'banana', 'cherry', 'pear'],
            'fruitPrice':[2500, 3800, 6000, 1200],
            'num' : [10, 5, 3, 8]}
fruitData

{'fruitName': ['apple', 'banana', 'cherry', 'pear'],
 'fruitPrice': [2500, 3800, 6000, 1200],
 'num': [10, 5, 3, 8]}

In [54]:
fruitName = fruitData['fruitName']
fruitName

['apple', 'banana', 'cherry', 'pear']

In [58]:
fruitFrame = DataFrame(fruitData, index=fruitName, columns=['fruitPrice', 'num'])
fruitFrame

fruitPrice  num
apple         2500   10
banana        3800    5
cherry        6000    3
pear          1200    8

In [60]:
fruitFrame.drop(['apple','cherry'])

fruitPrice  num
banana        3800    5
pear          1200    8

In [62]:
fruitFrame2 = fruitFrame.drop(['apple','cherry']) #삭제 후 새로운 변수로 넣게되면 원본은 보존하고 삭제된 데이터를 얻을 수 있다.
fruitFrame2
#여기까지는 행(row)을 삭제시키는 기능
#여러가지를 삭제하기 이해서는 리스트로 만들어서 삭제해야 함.

fruitPrice  num
banana        3800    5
pear          1200    8

In [65]:
fruitFrame3 = fruitFrame.drop('num', axis=1) #axis가 0이면 row단위로 해석. 따라서 axis에 1을 선언해주어야 열 단위로 해석해서 옵션 적용.
fruitFrame3

fruitPrice
apple         2500
banana        3800
cherry        6000
pear          1200

## 항목 추출하기

In [66]:
fruit = Series(data=[2500, 3800, 1200, 6000], index=['apple','banana','pear','cherry'])
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [67]:
fruit['apple':'pear']

apple     2500
banana    3800
pear      1200
dtype: int64

In [68]:
fruit['banana':'pear']

banana    3800
pear      1200
dtype: int64

In [95]:
fruitData = {'fruitName':['apple', 'banana', 'cherry', 'pear'],
            'fruitPrice':[2500, 3800, 6000, 1200],
            'num' : [10, 5, 3, 8]}
fruitData

{'fruitName': ['apple', 'banana', 'cherry', 'pear'],
 'fruitPrice': [2500, 3800, 6000, 1200],
 'num': [10, 5, 3, 8]}

In [96]:
fruitName=fruitData['fruitName']
fruitFrame=DataFrame(fruitData, index=fruitName, columns=['fruitPrice','num'])
fruitFrame

fruitPrice  num
apple         2500   10
banana        3800    5
cherry        6000    3
pear          1200    8

In [73]:
fruitFrame['fruitPrice'] #하나의 column만 추출할 수 있는데 이때 인덱스 값은 같이 나옴

apple     2500
banana    3800
cherry    6000
pear      1200
Name: fruitPrice, dtype: int64

In [74]:
fruitFrame['apple':'banana'] #행을 기준으로 추출할 때는 표 값으로 데이터 추출되는 듯.

fruitPrice  num
apple         2500   10
banana        3800    5

## 데이터 기본 연산

In [75]:
fruit1 = Series([2500, 3800, 1200, 6000], index=['apple','banana','pear','cherry'])
fruit1

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [76]:
fruit2=Series([3,2,9,5,10], index=['apple','orange','banana','cherry','mango'])
fruit2

apple      3
orange     2
banana     9
cherry     5
mango     10
dtype: int64

In [77]:
fruit1+fruit2 #인덱스 기준으로 합 계산

apple     2503.0
banana    3809.0
cherry    6005.0
mango        NaN
orange       NaN
pear         NaN
dtype: float64

In [79]:
fruitData1 = {'Ohio':[4,8,3,5], 'Texas':[0,1,2,3]}
fruitFrame1=DataFrame(fruitData1, index=['apple','banana','cherry','pear'], columns=['Ohio','Texas'])
fruitFrame1

Ohio  Texas
apple      4      0
banana     8      1
cherry     3      2
pear       5      3

In [80]:
fruitData2 = {'Ohio':[3,0,2,1,7], 'Colorado':[5,4,3,6,0]}
fruitFrame2=DataFrame(fruitData2, index=['apple','orange','banana','cherry','mango'], columns=['Ohio','Colorado'])
fruitFrame2

Ohio  Colorado
apple      3         5
orange     0         4
banana     2         3
cherry     1         6
mango      7         0

In [81]:
fruitFrame1 + fruitFrame2 #같은 인덱스가 있어야 합을 구해준다. 한쪽에만 있는 인덱스의 경우에도 NaN값으로 츌력

Colorado  Ohio  Texas
apple        NaN   7.0    NaN
banana       NaN  10.0    NaN
cherry       NaN   4.0    NaN
mango        NaN   NaN    NaN
orange       NaN   NaN    NaN
pear         NaN   NaN    NaN

## 데이터 정렬

In [82]:
fruit = Series([2500,3800,1200,6000], ['apple','banana','pear','cherry'])
fruit

apple     2500
banana    3800
pear      1200
cherry    6000
dtype: int64

In [83]:
fruit.sort_values(ascending=False) #ascending=False 내림차순 / =True 오름차순(디폴트는 True 오름차순이다.)

cherry    6000
banana    3800
apple     2500
pear      1200
dtype: int64

In [87]:
fruitFrame

fruitPrice  num
apple         2500   10
banana        3800    5
cherry        6000    3
pear          1200    8

In [86]:
fruitFrame.sort_index(ascending=False)

fruitPrice  num
pear          1200    8
cherry        6000    3
banana        3800    5
apple         2500   10

In [88]:
fruitFrame.sort_index(axis=1) #column순으로 정렬

fruitPrice  num
apple         2500   10
banana        3800    5
cherry        6000    3
pear          1200    8

In [89]:
fruitFrame.sort_index(axis=1, ascending=False)

num  fruitPrice
apple    10        2500
banana    5        3800
cherry    3        6000
pear      8        1200

In [97]:
fruitFrame.sort_values(by='fruitPrice') #정렬해야하는 값이 int, str이 섞여 있으면 오류가 출력된다.

fruitPrice  num
pear          1200    8
apple         2500   10
banana        3800    5
cherry        6000    3