In [1]:
import numpy as np

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
print(arr)

[1 2 3 4]


In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
np.empty((4,4))

array([[4.67296746e-307, 1.69121096e-306, 2.33646845e-307,
        1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306, 1.11260619e-306,
        8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306, 1.37962456e-306,
        1.69111861e-306],
       [1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        7.56599806e-307]])

In [17]:
np.arange(10)

array(10)

In [18]:
np.arange(0,100,5) #관계를 형성해서 데이터를 만드는 작업도 가능

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [19]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
arr.shape #몇 행 몇 열

(2, 3)

In [21]:
arr.ndim #2차원

2

In [22]:
arr.dtype #데이터타입

dtype('int32')

In [23]:
arr_int = np.array([1,2,3,4])
arr_int.dtype

dtype('int32')

In [24]:
arr_float = arr_int.astype(np.float64)
arr_float

array([1., 2., 3., 4.])

In [25]:
arr_float.dtype

dtype('float64')

In [26]:
#문자형 데이터 배열을 정수형 데이터 배열로 변환하기
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [28]:
arr_int=arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [29]:
#배열 연산

In [30]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [31]:
arr1+arr2 #각 위치의 숫자끼리 연산

array([[ 6,  8],
       [10, 12]])

In [32]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [33]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [34]:
np.multiply(arr1,arr2) #행렬의 곱이 아닌 각 배열 요소의 곱

array([[ 5, 12],
       [21, 32]])

In [ ]:
#1(0,0)1*2(0,0)5 + 1(0,1)2 * 2(1,0)7

In [35]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [36]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [38]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr[:2, 1:3] #행, 열 순서로 중복되는 부분 가져오기 slice
#슬라이싱한 배열을 수정하면 원본 배열도 바뀐다.

array([[2, 3],
       [5, 6]])

In [40]:
arr_1 = arr[:2, 1:3].copy() #arr과 arr_1이 별도의 저장공간이 되어 마음대로 수정 가능

array([[2, 3],
       [5, 6]])

In [41]:
arr[0,2]

3

In [42]:
arr[[0,1,2],[2,0,1]] #0행2열/1행0열/2행1열

array([3, 4, 8])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
idx=arr>3
idx

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
arr[idx]

array([4, 5, 6, 7, 8, 9])

In [47]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9])

## numpy 데이터 분석 사례

1.데이터 만들기(winequality-red.csv)
- https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

In [48]:
np.loadtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv")
#오류 메시지 원인 > 넘파이는 다 float실수만 인식할 수 있음. 문자열을 해석 불가. skiprows=1로 문제해결.

ValueError: could not convert string to float: '"fixed'

In [49]:
np.loadtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", skiprows=1)
#오류해석 : string을 float(실수)으로 가져갈 수 없다 > delimiter=';'로 오류 해결

ValueError: could not convert string to float: '7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5'

In [50]:
np.loadtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", delimiter=";", skiprows=1)

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [51]:
redwine=np.loadtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", delimiter=";", skiprows=1)
redwine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [53]:
redwine.shape

(1599, 12)

In [55]:
redwine.ndim

2

In [58]:
redwine.sum()

152084.78194

In [59]:
redwine.mean()

7.926036165311652

In [60]:
redwine.mean(axis=0) #컬럼값들의 평균
#axis 헷갈린다...

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [61]:
redwine.mean(axis=1) #행값의 평균

array([ 6.21198333, 10.25456667,  8.30825   , ...,  8.37347833,
        8.76795583,  7.7077075 ])

In [63]:
redwine[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [64]:
redwine[:,0].mean()

8.31963727329581

In [65]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [67]:
redwine.max(axis=1)

array([34., 67., 54., ..., 40., 44., 42.])

In [66]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])

In [68]:
redwine.min(axis=1)

array([0.   , 0.   , 0.04 , ..., 0.076, 0.075, 0.067])