## Numpy Quickstart
https://numpy.org/devdocs/user/quickstart.html

In [2]:
import pandas as pd
import numpy as np

#import matplot.pyplot as plt
#import seaborn as sns

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a = np.arange(15).reshape(3,-1) ; a
#reshape에 -1값은 자동으로 계산

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a1 = np.arange(24).reshape(2,3,-1) ; a1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
a.shape

(3, 5)

In [8]:
a1.shape

(2, 3, 4)

In [9]:
a.ndim

2

In [10]:
a1.ndim

3

In [11]:
a.dtype.name

'int32'

In [12]:
a.itemsize
#각각에 대한 바이트 사이즈

4

In [13]:
a1.itemsize

4

In [14]:
a.size
#요소수

15

In [15]:
a1.size

24

In [16]:
type(a)

numpy.ndarray

## Array Creation

In [17]:
a = np.array([2,3,4]); a

array([2, 3, 4])

In [18]:
b = np.array([1,2,3.5,5.1]);b

array([1. , 2. , 3.5, 5.1])

In [19]:
a.dtype
#정수

dtype('int32')

In [20]:
b.dtype
#실수

dtype('float64')

In [21]:
#a=np.array(1,2,3,4) >>> 오류
a=np.array([1,2,3,4]) ; a

array([1, 2, 3, 4])

In [22]:
from numpy import pi
np.linspace(0,2,9)
#arange와 다르게 필요한 숫자의 개수를 지정

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
pi

3.141592653589793

In [27]:
x=np.linspace(0,2*pi,100)
f=np.sin(x); f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Printing Arrays

In [28]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [29]:
np.arange(12).reshape(4,3)
#축이 두 개(2d)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.arange(24).reshape(2,3,4)
#축이 세 개(3d)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
np.arange(16).reshape(2,2,2,2)
#축이 네 개(4d)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [32]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [37]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [38]:
np.random.default_rng(1)

Generator(PCG64) at 0x25E5BCFA220

In [39]:
a=np.arange(16).reshape(2,2,2,2);a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [40]:
a.sum(axis=0)
#큰 덩어리에서 위치값의 합 (전체를 반으로 해서 합)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [41]:
a.sum(axis=1)
#중간 덩어리에서 위치값의 합 (위의 두개 합 / 아래 두개 합)

array([[[ 4,  6],
        [ 8, 10]],

       [[20, 22],
        [24, 26]]])

In [42]:
a.sum(axis=2)
#작은 덩어리에서 위치값의 합

array([[[ 2,  4],
        [10, 12]],

       [[18, 20],
        [26, 28]]])

In [48]:
def f(x,y):
    print('x=',x)
    print('y=',y)
    return 10*x + y

In [49]:
f(3,5)

x= 3
y= 5


35

In [50]:
np.fromfunction(f,(5,4), dtype=int)
#함수를 통해 5행 4열을 만든다.

x= [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
y= [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [51]:
b=np.fromfunction(f,(5,4), dtype=int)

x= [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
y= [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [52]:
b[2,3]

23

In [53]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [54]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [55]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [56]:
b[-1]

array([40, 41, 42, 43])

In [57]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [59]:
list(b.flat)

[0, 1, 2, 3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40, 41, 42, 43]

In [62]:
for i, element in enumerate(b.flat):
    print('i=', i,'**=', element)
    if i>3:
        break

i= 0 **= 0
i= 1 **= 1
i= 2 **= 2
i= 3 **= 3
i= 4 **= 10


In [ ]:
#argmax, argmin : 딥러닝 평가에서 많이 사용

In [64]:
a = np.arange(6).reshape(2,3) + 10 ;a

array([[10, 11, 12],
       [13, 14, 15]])

In [65]:
np.argmax(a)
#전체에서 가장 큰 숫자 위치

5

In [66]:
np.argmax(a, axis=0)
#x축기준으로 가장 큰 숫자, y축 위지

array([1, 1, 1], dtype=int64)

In [67]:
np.argmax(a, axis=1)
#y축 기준으로 가장 큰 숫자, x축 위치

array([2, 2], dtype=int64)